### Produts Index
GET http://localhost:3000/products?discount=true

### Produts Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "D&D Players Handbook",
  "price": "50",
  "description": "A lovely 5th edition handbook for your players.",
  "quantity": 6
}

### Products Show
GET http://localhost:3000/products/2

### Products Update
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "quantity": 6
}

### Products Destroy
DELETE http://localhost:3000/products/1

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Ace",
  "email": "ace@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "ace@gmail.com",
  "password": "password"
}