@domain = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMzMDQ4NDR9.5kyXdNY_MAIKtSJr5MgCQHc5COlOig7OChhFgwVTfCY

### Produts Index
GET {{ domain }}/products

### Produts Create
POST {{ domain }}/products
Content-Type: application/json
Authorization: Bearer {{ jwt }}


{
  "name": "D&D Players Handbook",
  "price": "50",
  "description": "A lovely 5th edition handbook for your players.",
  "quantity": 6,
  "supplier_id": 2
}

### Products Show
GET {{ domain }}/products/2

### Products Update
PATCH {{ domain }}/products/1
Content-Type: application/json

{
  "quantity": 6
}

### Products Destroy
DELETE {{ domain }}/products/1

### Users create (signup)
POST {{ domain }}/users
Content-Type: application/json

{
  "name": "Cheddar",
  "email": "cheddar@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{ domain }}/sessions
Content-Type: application/json

{
  "email": "cheddar@gmail.com",
  "password": "password"
}

### Orders index
GET {{ domain }}/orders
Authorization: Bearer {{ jwt }}

### Orders create
POST {{ domain }}/orders
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "product_id": 4,
  "quantity": 5
}

### Orders show
GET {{ domain }}/orders/3
Authorization: Bearer {{ jwt }}